### PR TITLE
change: update stock favicon.ico to be Keyman icon

### PR DESCRIPTION
**Pull request by megahirt**
This replaces the stock Angular favicon with the Keyman favicon.ico file from keyman.com

Note that the stock Angular favicon is actually a PNG file with greater resolution than the Keyman one which is a Windows ICO file.  Tested on Chrome and Firefox.

file command output:
stock-angular-favicon.ico:  PNG image data, 28 x 30, 8-bit/color RGBA, non-interlaced
keyman-favicon.ico: MS Windows icon resource - 1 icon, 16x16

Screenshot:
image

The primary motivation for this PR is to see myself on the status.keyman.com website :)

I don't have write access to status.keyman.com so I forked and PR'ed.

### CODE REVIEW

**Comment by megahirt** [comment]
Yup, there she is.

image

**Comment by darcywong00** [comment]
> I don't have write access to status.keyman.com so I forked and PR'ed.

I've added you as a collaborator  (for your future PRs 😄)

**Comment by darcywong00** [comment]
The team drive has a folder for branding resources.
Here's a 30x32 PNG
Keyman icon 30

**Comment by megahirt** [comment]
> 
> 
> The team drive has a folder for branding resources.
> Here's a 30x32 PNG

Cool, looks like keyman.com needs a favicon update as well then :)

**Comment by megahirt** [comment]
OK, this looks better with the PNG and transparency.  Here's my firefox with the transparency.

image

I force pushed the updated favicon so it should be good to go.

**Comment by mcdurdin** [comment]
Thank you for your contribution! I look forward to more in the future :)

**Comment by megahirt** [comment]
You're welcome :)  Wish I had the time for more meaningful PRs.

**Pull request merged**
